#!/bin/bash

echo "Are you sure you want to push? (Confirm that you aren't at school) [Y/n] "
read a

if [ $a = "y" ]
then
	git push origin main
	git push mirror main
	git pull origin main
else
	git push mirror main
	git pull mirror main
	echo "Make sure to run ./update once you get home."
fi

