#!/bin/bash

echo "Syncing the mirror with the main branch. Are you sure? [Y/n] "
read a

if [ $a = "y" ]
then
    git pull mirror main
    git add -A 
    git commit -m "Synchronization of mirror with main branch"
    git push origin main
else
    echo "Aborted"
fi
